# Generated by Django 5.2 on 2025-05-06 06:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
                ('department_head', models.CharField(max_length=20)),
                ('Tl_mail', models.CharField(default='teamlead1@gmail.com', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genders', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('Planned_Leave', models.IntegerField()),
                ('Sick_Leave', models.IntegerField()),
                ('Emergency_Leave', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(choices=[('SickLeave', 'SickLeave'), ('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_message', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_message', models.CharField(blank=True, max_length=100, null=True)),
                ('teamlead_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('HR', 'HR'), ('Manager', 'Manager'), ('IT Support', 'IT Support'), ('Admin', 'Admin'), ('Team Lead', 'Team Lead')], max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppOne.department_table')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.gender_table')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tl_status', models.CharField(default='pending', max_length=20)),
                ('reasign_status', models.CharField(blank=True, max_length=40, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.leavetype')),
                ('messages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppOne.messages')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.employee')),
                ('assigned_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppOne.department_table')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.employee')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AppOne.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Total_leave_remaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_sickleave', models.IntegerField()),
                ('remaining_plannedleave', models.IntegerField()),
                ('remaining_emergencyleave', models.IntegerField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Total_leaves_taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_sickleave', models.IntegerField()),
                ('approved_plannedleave', models.IntegerField()),
                ('approved_emergencyleave', models.IntegerField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.employee')),
            ],
        ),
    ]
