# Generated by Django 5.2 on 2025-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0002_remove_leaverequest_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reasign_status',
            field=models.CharField(blank=True, default='pending', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave'), ('SickLeave', 'SickLeave')], max_length=50),
        ),
    ]
