# Generated by Django 5.2 on 2025-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0003_alter_leaverequest_reasign_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='query_status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gender_table',
            name='Genders',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('SickLeave', 'SickLeave'), ('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave')], max_length=50),
        ),
    ]
