# Generated by Django 5.2 on 2025-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_leaverequest_query_status_alter_gender_table_genders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reasign_status',
            new_name='re_raise_status',
        ),
        migrations.AlterField(
            model_name='gender_table',
            name='Genders',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave'), ('SickLeave', 'SickLeave')], max_length=50),
        ),
    ]
