# Generated by Django 5.2 on 2025-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0005_rename_reasign_status_leaverequest_re_raise_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='query_status',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='re_raise_status',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='tl_status',
        ),
        migrations.AlterField(
            model_name='gender_table',
            name='Genders',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('PlannedLeave', 'PlannedLeave'), ('SickLeave', 'SickLeave'), ('EmergencyLeave', 'EmergencyLeave')], max_length=50),
        ),
    ]
