# Generated by Django 5.2 on 2025-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0006_remove_leaverequest_query_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='tl_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave'), ('SickLeave', 'SickLeave')], max_length=50),
        ),
    ]
