# Generated by Django 5.2 on 2025-05-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0007_leaverequest_tl_status_alter_leavetype_leave_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('SickLeave', 'SickLeave'), ('EmergencyLeave', 'EmergencyLeave'), ('PlannedLeave', 'PlannedLeave')], max_length=50),
        ),
        migrations.CreateModel(
            name='Assigment_table_tl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.leaverequest')),
                ('assigned_tl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.department_table')),
            ],
        ),
    ]
