# Generated by Django 5.2 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0008_alter_leavetype_leave_name_assigment_table_tl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='tl_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('PlannedLeave', 'PlannedLeave'), ('EmergencyLeave', 'EmergencyLeave'), ('SickLeave', 'SickLeave')], max_length=50),
        ),
    ]
